# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name : Python CI

# Triggger the workflow on any push to main branch or pull request
# using the on keyword
# I can use diffrenet branches also
# step 1: Define the trigger for the workflow
on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main
# Define the job to 
# may have multiple jobs
# each job will run in a fresh instance of the virtual environment
# using the jobs keyword
# each job will have multiple steps
# using the steps keyword
# each step will run a single command

jobs:
    test:
        runs-on: ubuntu-latest 
        # Use the latest version of Ubuntu container to test the code
        # step 2: Define the steps to be run in the job
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              # Step 3: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'
            # step 4 : Install dependencies and run tests
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            # step 5: Run the tests using pytest
            - name: Run tests
              run: |
                  pytest   
        # it will start looking for the test files in the root directory 
        # if not found it will look in the src directory
        # if found it will run the test cases
        # if all the test cases pass the job will be marked as successful
        # if any test case fails the job will be marked as failed
        # the status of the job will be reflected in the pull request
        # if the job is successful the pull request can be merged
        # if the job fails the pull request cannot be merged
        # the status of the job can be seen in the Actions tab of the repository
